# $Id: Makefile,v 1.1.1.1 2006/11/29 09:28:02 lizhijie Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

# DEFINES += 
#

PACKAGES += UTIL PTHREAD LIBCEXT LIBXML


# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS = \
        parse3tupleTest.cxx \
        GetOptTest.cxx \
        ParsePairTest.cxx \
        ParsePairStringTest.cxx \
        

	
include $(BUILD)/Makefile.post
