/*
* $Id: cgi_navigate.h,v 1.11 2007/09/15 19:45:14 lizhijie Exp $
*/

#ifndef	__CGI_NAVIGATE_H__
#define	__CGI_NAVIGATE_H__

#define	NAVIGATE_NAME_LENGTH			128

#define	FOLDER_TREE_NAME					"foldersTree"

//#define	_(text)								(text)

typedef enum
{
	NAVIFATE_TARGET_NEW_WINDOW	= 0,
	NAVIGATE_TARGET_MAIN_FRAME		= 2
}NAVIGATE_TARGET_TYPE;


typedef enum
{
	NAVI_FOLDER_ROOT			=	1,
	NAVI_FOLDER_NETWORK,
	NAVI_FOLDER_SYSTEM,
	NAVI_FOLDER_SOFT_HARDWARE,
	NAVI_FOLDER_UPDTAE,
	NAVI_FOLDER_BACKUP,
	NAVI_FOLDER_RESTORE,
	NAVI_FOLDER_SYSTEM_DISK,
	NAVI_FOLDER_SERVICES,
	NAVI_FOLDER_SERVICES_CONFIG,
	NAVI_FOLDER_SERVICES_DDNS,
	NAVI_FOLDER_FIREWALL,
	NAVI_FOLDER_FIREWALL_RULE,
	NAVI_FOLDER_VPN,
	NAVI_FOLDER_VPNSERVER,
	NAVI_FOLDER_VPNACCOUNT,
	NAVI_FOLDER_VPNCLIENT,
	NAVI_FOLDER_QOS,
	NAVI_FOLDER_DIALPLAN,
	NAVI_FOLDER_DIALPLAN_TELE,
	NAVI_FOLDER_DIALPLAN_IP,
	NAVI_FOLDER_DIALPLAN_IP_RULE,
	NAVI_FOLDER_PBX,
	NAVI_FOLDER_PBX_EXT,
	NAVI_FOLDER_PBX_LINES,
	NAVI_FOLDER_PBX_OTHERS,
#if __WITH_NEW_STC__
	NAVI_FOLDER_PBX_HW_CHECK,
#endif
	NAVI_FOLDER_SIP_UA,
	NAVI_FOLDER_SIP_UA_OTHERS,
	NAVI_FOLDER_SIP_SERVER,
	NAVI_FOLDER_ALERT_VOICE,
	NAVI_FOLDER_RUNTIME,			/* runtime info for our critical tasks */
#if WITH_MESH	
	NAVI_FOLDER_MESH,
	NAVI_FOLDER_MESH_CONTROL,
	NAVI_FOLDER_MESH_STATE,
#endif	
	NAVI_FOLDER_WIRELESS,
	NAVI_FOLDER_WIRELESS_AODV,
	NAVI_FOLDER_MAIL,
	NAVI_FOLDER_MAIL_USER,
	NAVI_FOLDER_SERVERS,
	NAVI_FOLDER_SERVER_WWW,
	NAVI_FOLDER_VIDEO,
	NAVI_FOLDER_NOT_EXIST
}FOLDER_ID;

struct _menu_folder
{
	FOLDER_ID					id;
	char							name[NAVIGATE_NAME_LENGTH];

	char							menuName[NAVIGATE_NAME_LENGTH];
	char							iconName[NAVIGATE_NAME_LENGTH];
	char							hReference[NAVIGATE_NAME_LENGTH];

	FOLDER_ID					parentId;

	int							where;
};

struct _menu_item
{
	NAVIGATE_TARGET_TYPE		target;
	
	char							name[NAVIGATE_NAME_LENGTH];
	char							alertMsg[NAVIGATE_NAME_LENGTH];
	char							iconName[NAVIGATE_NAME_LENGTH];

	char							hReference[NAVIGATE_NAME_LENGTH];

	FOLDER_ID					folderId;

	int							where;
};

typedef	struct _menu_folder		NAVIGATE_FOLDER;
typedef	struct _menu_item		NAVIGATE_MENU_ITEM;

#define	MENU_WHERE_BASE			0x00000001
#define	MENU_WHERE_IPPBX			0x00000002
#define	MENU_WHERE_SERVICES		0x00000004
#define	MENU_WHERE_SERVERS		0x00000008
#define	MENU_WHERE_VIDEO			0x00000010
#define	MENU_WHERE_ANYWHERE	0xFFFFFFFF

typedef		enum
{
	WEB_TYPE_BASE = 0,
	WEB_TYPE_IP_PBX,
	WEB_TYPE_SERVICES,
	WEB_TYPE_SERVERS,
	WEB_TYPE_VIDEO,
	WEB_TYPE_INVALIDATE
}WEB_TYPE_T;

/* for navigate.cgi and content.cgi */
typedef	struct	
{
	llist				cgiVariables;
	WEB_TYPE_T		type;

	int				where;
	
}BASE_INFO;

#define	CGI_NAVIGATE_KEYWORD_BASE			"base"
#define	CGI_NAVIGATE_KEYWORD_IPPBX			"ippbx"
#define	CGI_NAVIGATE_KEYWORD_SERVICES		"services"
#define	CGI_NAVIGATE_KEYWORD_SERVERS		"servers"
#define	CGI_NAVIGATE_KEYWORD_VIDEO			"video"

#endif

