# $Id: Makefile,v 1.1.1.1 2006/11/29 09:28:02 lizhijie Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

# DEFINES += 
#

PACKAGES += UTIL PTHREAD


# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS = \
        vmd5sum.c
	
	
include $(BUILD)/Makefile.post
