# $Id: Makefile,v 1.1.1.1 2006/11/29 09:28:02 lizhijie Exp $

BUILD = ../../build

include $(BUILD)/Makefile.pre

DEFINES += USE_PTHREADS

PACKAGES += PTHREAD RTP UTIL QUICKNET

VERIFY_TESTCASES = \
	EndianVerify.cxx

include $(BUILD)/Makefile.post
