# $Id: Makefile,v 1.1.1.1 2006/11/29 09:28:02 lizhijie Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

# DEFINES += 
#

PACKAGES += TRANSPORT UTIL PTHREAD


# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS = \
        cpLogTestPriorities.cxx \
        cpLogTestTrafficGenerator.cxx \
    	VLogTest.cxx \
	
	
	
include $(BUILD)/Makefile.post
