# $Id: Makefile,v 1.1.1.1 2006/11/30 16:27:09 lizhijie Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

PACKAGES += SDP2 UTIL PTHREAD

# names of programs (e.g. test programs) to be compiled
#

# names of programs (e.g. test programs) to be compiled
#TESTPROGRAMS = \
#	Sdp2Test.cxx 

VERIFY_TESTCASES = \
	Sdp2AttributeTest.cxx\
	Sdp2SessionTest.cxx\
	Sdp2ConnectionTest.cxx

include $(BUILD)/Makefile.post
