#!/bin/bash
#
# RCSID $Id: ttn,v 1.1.1.1 2006/11/29 08:55:39 lizhijie Exp $
#
# This script is OBSOLETE -- rgb, May 6th, 1998
set +v
insmod ipsec.o
tncfg attach ipsec0 eth2
ifconfig ipsec0 10.2.0.143 up netmask 255.255.0.0
route del 10.2.0.0
route add -net 10.2.0.0 netmask 255.255.0.0 dev ipsec0


#
# $Log: ttn,v $
# Revision 1.1.1.1  2006/11/29 08:55:39  lizhijie
# AS600 Kernel
#
# Revision 1.1.1.1  2005/07/08 09:46:23  lizhijie
# Linux-2.4.24 integrated Intel Access Library 2.0
#
# Revision 1.1.1.1  2004/08/17 02:50:02  lizhijie
# linux-2.4.24 for IXP422
#
# Revision 1.3  1999/04/06 04:54:36  rgb
# Fix/Add RCSID Id: and Log: bits to make PHMDs happy.  This includes
# patch shell fixes.
#
#
