/*
* $Id: pbx_program.h,v 1.4 2007/07/03 20:35:32 lizhijie Exp $
*/
#ifndef	__PBX_PROGRAM_H__
#define	__PBX_PROGRAM_H__

typedef	enum
{
	PROGRAM_CMD_NONE					=	0,

	/* following are manipulate commands */
	PROGRAM_CMD_OP_GET_PHONENUMBER,
	PROGRAM_CMD_OP_RECORD,
	PROGRAM_CMD_OP_RECORD_PLAY,

	PROGRAM_CMD_OP_FACTORY_DEFAULT,
	PROGRAM_CMD_OP_RESET,

	PROGRAM_CMD_OP_REPLACE,
	PROGRAM_CMD_OP_CALL_CONFERENCE,
	
	/* following are configuration commands */
	PROGRAM_CMD_CFG_TRACK_MODE,
	PROGRAM_CMD_CFG_NODIAL_ACTION,
	PROGRAM_CMD_CFG_LINE2LINE,
	PROGRAM_CMD_CFG_DIFFER_RING,
	PROGRAM_CMD_CFG_GROUP_CALL,
	PROGRAM_CMD_CFG_SPECIAL_FIRST,
	PROGRAM_CMD_CFG_CALLERID_MODE,
	
	PROGRAM_CMD_CFG_SIGNAL_TYPE,

	PROGRAM_CMD_CFG_IP_PREFIX,
	PROGRAM_CMD_CFG_PSTN_PREFIX,

	/* 2 integers as parameters */
	PROGRAM_CMD_CFG_LINE_STATUS,
	PROGRAM_CMD_CFG_ACCOUNT_AUTHOR,
	PROGRAM_CMD_CFG_PSTN_GROUP,
	PROGRAM_CMD_CFG_PSTN_CONSOLE,	/* an EXT as console of one PSTN line */

	PROGRAM_CMD_CFG_EXT_AUTHORITY,
	PROGRAM_CMD_CFG_EXT_CALLER_ID,
	
	PROGRAM_CMD_CFG_BUSY_EXT,
	PROGRAM_CMD_CFG_SECRET_EXT,
	PROGRAM_CMD_CFG_EXT_GROUP,
	PROGRAM_CMD_CFG_EXT_DIALOUT_MODE,

	PROGRAM_CMD_CFG_EXT_DELAY_2_LINE,
	PROGRAM_CMD_CFG_EXT_CALLWAIT,
	PROGRAM_CMD_CFG_EXT_NODISTURB,
	PROGRAM_CMD_CFG_EXT_DIFFER_RINGING,

	PROGRAM_CMD_CFG_PASSWD_LINE2LINE,
	PROGRAM_CMD_CFG_PASSWD_SYSTEM,
	PROGRAM_CMD_CFG_PASSWD_ACCOUNT,
	PROGRAM_CMD_CFG_SPECIAL_NUMBER,
	PROGRAM_CMD_CFG_EXT_PHONE_NUMBER,

	PROGRAM_CMD_CFG_EXT_LEFT_TIME,
	PROGRAM_CMD_CFG_EXT_TIMEOUT,
	
	PROGRAM_CMD_CFG_TRANSFER_LEFT,
	PROGRAM_CMD_CFG_TRANSFER_NIGHT,
	PROGRAM_CMD_CFG_TRANSFER_DENY,		/* black list */
	PROGRAM_CMD_CFG_TRANSFER_UNCONDITIONAL,
	PROGRAM_CMD_CFG_NIGHT_SERVICE_TIME,

	PROGRAM_CMD_MAX_NUMBER,
}PBX_PROGRAM_CMD;

#define	PBX_RERING_COUNT			3

typedef	struct
{
	INT8U	currentCmd;
	INT8U	extIndex;
}program_context;


typedef	struct _pbx_program_handle_t
{
	INT8U		digits;			/* 2 digits which is used to determine operation */
	INT8U		cmd;
	INT8U 		(code *handle)(INT8U extIndex,INT8U cmd, phone_digits_t xdata *dialingDigits);
}pbx_program_handle_t;

/* cancel operation is handled by every command */
typedef struct _pbx_program_exit_handle_t
{
	INT8U		cmd;
	INT8U 		(code *handle)(INT8U extIndex);
}pbx_program_exit_handle_t;


#endif

