# $Id: Makefile,v 1.1.1.1 2006/11/29 09:28:02 lizhijie Exp $

BUILD = ../../../build

include $(BUILD)/Makefile.pre

PACKAGES += TRANSPORT UTIL LIBXML PTHREAD


# names of programs (e.g. test programs) to be compiled
#

SAMPLEPROGRAMS = \
        PerfSample.cxx
        
TESTPROGRAMS = $(SAMPLEPROGRAMS)
	
	
include $(BUILD)/Makefile.post
